services:
  - type: web
    name: assignment-plagiarism-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd flask-server && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true